// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiwLPamzYIZftkm6kXTC3EsQWF2RhnrCE',
    appId: '1:18522013448:web:8264b931a9d4f2cfd3f6bd',
    messagingSenderId: '18522013448',
    projectId: 'mylibrary-32c9f',
    authDomain: 'mylibrary-32c9f.firebaseapp.com',
    storageBucket: 'mylibrary-32c9f.firebasestorage.app',
    measurementId: 'G-T8NCV16JLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBmEecGr1i9qNqx94Ap6pVbsQFjS7bycA',
    appId: '1:18522013448:android:733881bf881a6a94d3f6bd',
    messagingSenderId: '18522013448',
    projectId: 'mylibrary-32c9f',
    storageBucket: 'mylibrary-32c9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD80rGNWz369Tm62zgmrffj22L7Dy_3dSc',
    appId: '1:18522013448:ios:dae10377ed15b575d3f6bd',
    messagingSenderId: '18522013448',
    projectId: 'mylibrary-32c9f',
    storageBucket: 'mylibrary-32c9f.firebasestorage.app',
    iosBundleId: 'com.example.mylibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD80rGNWz369Tm62zgmrffj22L7Dy_3dSc',
    appId: '1:18522013448:ios:dae10377ed15b575d3f6bd',
    messagingSenderId: '18522013448',
    projectId: 'mylibrary-32c9f',
    storageBucket: 'mylibrary-32c9f.firebasestorage.app',
    iosBundleId: 'com.example.mylibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiwLPamzYIZftkm6kXTC3EsQWF2RhnrCE',
    appId: '1:18522013448:web:292b8b47c6b28ef5d3f6bd',
    messagingSenderId: '18522013448',
    projectId: 'mylibrary-32c9f',
    authDomain: 'mylibrary-32c9f.firebaseapp.com',
    storageBucket: 'mylibrary-32c9f.firebasestorage.app',
    measurementId: 'G-37QT2CQ5BJ',
  );
}
